creation_rules:
  # The following regex matches any file in the `secrets/` directory or a file named `vault.yaml` in any directory.
  - path_regex: (?<secrets_dir>^secrets/)(?<secrets_filename>.*$)|(?<preceding_path>^.*)(?<local_secrets_filename>vault\.yaml)
    key_groups:
      - pgp:
        age:
          - age1am4dcpefn4dlcnwtj2g3pmcc4djwuvktl89yuy09ha54l0t3rc2sh6qudy
