# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [(modulesPath + "/installer/scan/not-detected.nix")];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = [
      "size=8G"
      "mode=755"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/59bbc31f-76ef-428b-bf04-b88f5352c68b";
    fsType = "btrfs";
    options = ["subvol=nix"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/59bbc31f-76ef-428b-bf04-b88f5352c68b";
    fsType = "btrfs";
    options = ["subvol=home"];
  };

  fileSystems."/root" = {
    device = "/dev/disk/by-uuid/59bbc31f-76ef-428b-bf04-b88f5352c68b";
    fsType = "btrfs";
    options = ["subvol=roothome"];
  };

  fileSystems."/persistent" = {
    device = "/dev/disk/by-uuid/59bbc31f-76ef-428b-bf04-b88f5352c68b";
    fsType = "btrfs";
    options = ["subvol=persistent"];
    neededForBoot = true;
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/91E9-B88D";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/mnt/HD2" = {
    device = "/dev/disk/by-uuid/48475dc3-717f-457b-8bf8-49e4ceec6001";
    fsType = "btrfs";
  };

  fileSystems."/mnt/archive" = {
    device = "/dev/disk/by-uuid/075f12a2-6171-44ae-abb1-75f2f1b1fd54";
    fsType = "btrfs";
  };

  fileSystems."/etc/nixos" = {
    device = "/dev/disk/by-uuid/48475dc3-717f-457b-8bf8-49e4ceec6001";
    fsType = "btrfs";
    options = ["subvol=NixOS"];
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp11s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
